server:
  port: 8080
  servlet:
    context-path: /community

# thymeleafProperties & DataSourceProperties
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  # MailProperties
  mail:
    host: smtp.qq.com
    username: 952710554@qq.com
    password: bsnplvnddkisbgae
  # redisProperties
  redis:
    database: 1
    host: localhost
    port: 6379
  # kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  # ElasticSearchProperties
#  data:
#    elasticsearch:
#      cluster-name: dabai
#      cluster-nodes: 127.0.0.1:9300
  # TaskExcecutionProperties
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    # TaskSchedulingProperties
    scheduling:
      pool:
        size: 5
  # QuartzProperties
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO #如果使用集群，instanceId必须唯一，设置成AUTO
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          isClustered: true
        threadPool:
          class: org.quartz.simpl.SimpleThreadPool
          threadCount: 5
# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dabai.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true


# logger
#logging:
#  level:
#    com:
#      dabai:
#        community: debug

# 自定义配置community
community:
  path:
    domain: http://localhost:8080
    upload: D:/work/data/upload

elasticSearch:
  url: 127.0.0.1:9200
